name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check if there's a newer version

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1  # Check if there's a newer version
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1  # Use a specific version
      with:
        args: --acl public-read --follow-symlinks --delete s3://kongos3bucket/
