name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to the latest version (assuming v3 is the latest).

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 # Updated to the latest version (assuming v2 is the latest).
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync to S3
      run: |
        aws s3 sync . s3://kongos3bucket/ --delete

    - name: Invalidate CloudFront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id 	https://dcqmkxe5ixuxs.cloudfront.net --paths "/*"
